### ISSUE TITLE
I got it working in FL studio FX rack but it does not recognize the cmajor vst as a sampler based instrument

### ISSUE THREAD

**Issue by JayDeeRC** [SoundStacks/cmajor#21] opened 2023-08-07 04:29 UTC
Just wondering what needs to be done here as I cannot test any of the midi based exmaples or the sampler based ones (piano etc.)

**Comment by LucasThompson** [comment] 2023-09-14 17:42
Could you provide some more info about what you are experiencing here?

Reading between the lines, is it that you are only able to get effects plugins to work in FL Studio, and not any of the synth examples?

I'll need to get a copy of FL Studio in order to debug further, but in the meantime any more info you can provide is appreciated.

**Comment by LucasThompson** [comment] 2023-09-14 18:16
Additionally, are you talking about using the CmajPlugin to load patches from within FL Studio? Or are you generating a JUCE plugin?

If it is the first, then I suspect the issue is that the CmajPlugin is an effect plugin, not an instrument. We could consider shipping multiple plugins, but usually there is a way to still get the DAW to route MIDI to it.

**Comment by JayDeeRC** [comment] 2023-09-14 18:25
Not much further to add here  youll see once you download FL. They have a
pretty clear distinction what is a "sampler" vst and an "effect" vst. The
current iterarion of the plugin is only recognized as an effect plugin and
rgus cannot be loaded onto the sampler rack for any sort of audio
generation.

**Comment by LucasThompson** [comment] 2023-09-15 14:48
Thanks. You're right, the current version of CmajPlugin is an effect plugin, as I mentioned in my previous post. This isn't specific to FL Studio. Most DAWs provide a way to get MIDI / events into the plugin though.

I've attached an example video of one way to workaround this in FL. It involves putting the "Midi Out" generator in front of the effect, and then setting a midi input port for the CmajPlugin. You should also be able to get external MIDI input just be setting an input port for the plugin.

I appreciate that this isn't the most straightforward way to get instruments working, but there is at least a functional workaround. Our CmajPlugin is currently primarily meant for developing patches within a DAW environment, which are then intended to be exported to a dedicated plugin (our exported plugins are correctly categorised as instruments or effects).

I hope this helps. We'll consider shipping two versions of every plugin target in the future, or finding other ways to improve this as we improve our plugin, but in the meantime I will close this issue.

https://github.com/SoundStacks/cmajor/assets/5403370/f1f5090d-3a7e-4b32-bc69-329185ebbd8a

**Closed by LucasThompson** 2023-09-15 14:48 UTC
